development:
  adapter: postgresql
  encoding: unicode
  database: sms_development
  pool: 5
  username: jirka
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: sms_test
  pool: 5
  username: jirka
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: sms_production
  pool: 5
  username: jirka
  password:
